####
## 예외 처리
####
#### ► [_01_TryCatch_230425] & [_02_Catch_230425]
- 프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 예외 처리 실습
- (1) try-catch문: 예외가 발생할 가능성이 있는 하나의 try블럭과 여러 예외를 처리할 수 있는 하나 이상의 catch블럭으로 구성
- (2) 멀티 catch문: '|' 기호를 사용해 여러 catch블럭을 하나의 catch블럭으로 연결
####
#### ► [_03_Throw_230426]
- 키워드 throw를 사용해 프로그래머가 고의로 예외를 발생시키는 실습
####
#### ► [_04_Finally_230426]
- 예외 발생 여부와 관계없이 항상 수행되어야 할 코드를 포함할 목적으로 사용하는 finally블럭 실습
- 💡 finally블럭은 try-catch문의 마지막에 위치한다.
- 💡 예외가 발생한 경우엔 'try -> catch -> finally', 예외가 발생하지 않은 경우엔 'try -> finally' 순으로 실행된다.
####
#### ► [_05_TryWithResources_230426]
- 입출력에 사용되는 클래스 중, 자원 반환을 위해 자동으로 객체의 close()가 호출되는 try-with-resources문 실습
- 💡 try-with-resources문에 의해 자동으로 객체의 close()가 호출되려면, 클래스가 AutoCloseable 인터페이스를 구현한 것이어야 한다.
####
#### ► [_06_CustomException_230427]
- 기존에 정의된 예외 클래스 외에 프로그래머가 필요에 따라 새로운 예외 클래스를 정의하는 사용자 정의 예외 실습
####
#### ► [_07_Throws_230427]
- 예외가 발생한 메서드와 호출한 메서드 양쪽에서 예외 처리가 가능하도록 만드는 예외 되던지기(exception re-throwing) 실습
- 💡 예외가 발생할 메서드는 try-catch문을 사용해 예외 처리를 함과 동시에 메서드 선언부에 발생할 예외를 throws에 지정해 줘야 한다.
####
